title: Dev Scent Choi Blog
email: chlgudwns10@gmail.com
description: >-
  개발 기록 및 기술 블로그입니다.
baseurl: "/dev-scen-choi.io"
url: "https://dev-scent-choi.github.io"

theme: minima

# Minima 설정
minima:
  skin: classic

# Markdown 설정
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
